

class CallBackBaseException(Exception):
    def __init__(self):
        pass